# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Code Analyze

on: [push, workflow_dispatch]

jobs:
  analyze_mobile_app:
    runs-on: ubuntu-latest
    container:
      image: dart:latest

    steps:
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1
        with:
          version: 3.0.5

      - name: Install App dependencies
        run: flutter pub get
        working-directory: remote_car_app

      - name: Analyze source code
        run: flutter analyze --fatal-infos
        working-directory: remote_car_app

  analyze_embedded_app:
    runs-on: ubuntu-latest
    container:
      image: dart:latest

    steps:
      - name: Install Embedded dependencies
        run: dart pub get
        working-directory: embedded_controller

      - name: Analyze source code
        run: dart analyze --fatal-infos
        working-directory: embedded_controller

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      #- name: Run tests
        #run: dart test
